### ISSUE TITLE
Enable recursive dependency resolution in pipr

### ISSUE THREAD

**Issue by onyb** [yahoo/pipr#28]
`pipr` could use a switch like `-R` to recursively get a project-wide dependency information. Currently a user needs to do it for each file individually.

**Comment by yashbathia** [comment]
@onyb : Just realized we use -r parameter to create a requirements.txt file with pipr. Need to name the switch for recursive dependency differently or change the flag for creating requirements.txt.

**Comment by onyb** [comment]
@yashbathia: A lot of UNIX tools do this (eg, `-f` vs `-F`). Having said that, we can make do with a different switch like `-f dev-requirements.txt`. Many Python projects have different sets of requirements (test, dev, production, etc).
